build:
  image: cognoma/sandbox:latest
  commands:
    - python list_contributors.py

    - git config user.email "cognoma@greenelab.com"
    - git config user.name "cognoma"
    - git config --global push.default simple
    - git remote set-url origin https://github.com/cognoma/sandbox

    - git checkout master
    - git pull
    - git add sandbox_contributors.md
    - git commit -a -m "Drone Build [skip ci] [ci skip]"
    - git remote set-url origin https://gwaygenomics:$$GIT_PUBLISH_KEY@github.com/cognoma/sandbox.git
    - git stash
    - git push

branches:
  - staging
